server:
  port: 8003

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service_customer
        uri: lb://SPRING-CLOUD-CONSUMER
        order: 0
        predicates:
        - Path=/customer/**
        filters:
          - StripPrefix=1
          - AddResponseHeader=X-Response-Default-Foo, Default-Bar


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/        
      
logging:
  level:
    org.springframework.cloud.gateway: debug      